hydra:
  admin_api: "http://localhost:5445"
  public_api: "http://localhost:5444"
keto:
  read_api: "http://localhost:4466"
  write_api: "http://localhost:4467"
kratos:
  admin_api: "http://localhost:4434"
  public_api: "http://localhost:4433"  
workload:
  readers: 10 
  read_ratio: 2
  duration_sec: 120
